apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restward.fullname" . }}-config
  labels:
    {{- include "restward.labels" . | nindent 4 }}
data:
  ASPNETCORE_URLS: "http://+:5000"
  Cors__Origins__0: "http://{{ .Values.ingress.host }}"
