{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin" (include "restward.fullname" .))) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restward.fullname" . }}-admin
  labels:
    {{- include "restward.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existingSecret }}
  admin-api-key: {{ index $existingSecret.data "admin-api-key" }}
  {{- else }}
  admin-api-key: {{ randAlphaNum 48 | b64enc }}
  {{- end }}
