apiVersion: v1
kind: Secret
metadata:
  name: restward-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: REPLACE_AT_DEPLOY_TIME
  ConnectionStrings__DefaultConnection: REPLACE_AT_DEPLOY_TIME
